# Generated by Django 2.2.7 on 2019-11-13 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OUTCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='kuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OUTCity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='otkuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.InCity'),
        ),
    ]
