# Generated by Django 2.2.7 on 2019-11-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191113_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.CharField(max_length=100),
        ),
    ]
