# Generated by Django 2.2.7 on 2019-11-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191113_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kolichestvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolichestvo', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='kolichestvo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Kolichestvo'),
        ),
    ]
