# Generated by Django 2.2.7 on 2019-11-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191113_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kolichestvo',
            name='kolichestvo',
            field=models.CharField(max_length=10),
        ),
    ]
