# Generated by Django 2.2.7 on 2019-11-15 16:34

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('orders', '0012_auto_20191115_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finish',
            new_name='InCity',
        ),
        migrations.RenameModel(
            old_name='Start',
            new_name='OUTCity',
        ),
    ]
