# Generated by Django 2.2.7 on 2019-11-15 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('orders', '0013_auto_20191115_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OUTCity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='otkuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.InCity'),
        ),
    ]
