# Generated by Django 2.2.7 on 2019-11-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20191115_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kolichestvo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Kolichestvo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='kuda',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Finish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='otkuda',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Start'),
        ),
    ]
