# Generated by Django 2.2.7 on 2019-11-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20191116_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
