# Generated by Django 2.2.7 on 2019-11-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20191120_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='detey',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
