# Generated by Django 2.2.7 on 2019-11-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_detey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='detey',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
