# Generated by Django 2.2.7 on 2019-11-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20191130_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deteydescr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='detey',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
