# Generated by Django 3.0 on 2019-12-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20191130_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.CharField(max_length=200),
        ),
    ]
