# Generated by Django 2.2.7 on 2019-11-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferValencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ispanename', models.CharField(max_length=20)),
                ('pricelehkovoy', models.CharField(max_length=5)),
                ('priceminiven', models.CharField(max_length=5)),
                ('pricemikroavto', models.CharField(max_length=5)),
            ],
        ),
    ]
