# Generated by Django 2.2.7 on 2019-11-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(choices=[('1', 'Из аеропорта Аликанте'), ('2', 'Из ареопорта Валенсии')], max_length=20)),
            ],
        ),
    ]
