# Generated by Django 2.2.7 on 2019-11-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='type_car',
            field=models.CharField(choices=[('1', 'Из аеропорта Аликанте'), ('2', 'Из ареопорта Валенсии')], default='1', max_length=20),
        ),
    ]
