# Generated by Django 2.2.7 on 2019-11-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_calculate_type_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate',
            name='type_car',
            field=models.CharField(choices=[('1', '1-4 пассажира,2-3 багажных места (легковой автомобиль)'), ('2', '5-6 пассажиров,4-5 багажных мест (минивэн)'), ('2', '7-8 пассажиров,6-8 багажных мест (микроавтобус)')], default='1', max_length=20),
        ),
    ]
