# Generated by Django 2.2.7 on 2019-11-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191122_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='kuda',
            field=models.CharField(choices=[('1', 'КАМПЕЛЬО /EL CAMPELLO'), ('2', 'ВИЛЬЯХОЙОСА / VILLAJOYOSA'), ('2', 'ФИНЕСТРАТ / FINESTRAT')], default='1', max_length=20),
        ),
    ]
