# Generated by Django 2.2.7 on 2019-11-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191122_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
