# Generated by Django 2.2.7 on 2019-11-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_calculate_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(blank=True, max_length=20, null=True)),
                ('type_car', models.CharField(blank=True, max_length=50, null=True)),
                ('kuda', models.CharField(choices=[('1', 'КАМПЕЛЬО /EL CAMPELLO'), ('2', 'ВИЛЬЯХОЙОСА / VILLAJOYOSA'), ('2', 'ФИНЕСТРАТ / FINESTRAT')], max_length=50)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
