# Generated by Django 2.2.7 on 2019-11-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_calculator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calculator',
        ),
    ]
