# Generated by Django 2.2.7 on 2019-11-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20191128_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculate',
            name='kuda',
            field=models.CharField(choices=[('1', 'КАМПЕЛЬО /EL CAMPELLO'), ('2', 'ВИЛЬЯХОЙОСА / VILLAJOYOSA'), ('3', 'ФИНЕСТРАТ / FINESTRAT'), ('4', 'БЕНИДОРМ / BENIDORM'), ('5', 'АЛЬБИР / ALBIR'), ('6', 'АЛТЕА / ALTEA'), ('7', 'КАЛЬПЕ / CALPE'), ('8', 'БЕНИССА / BENISSA'), ('9', 'ТЕУЛАДА / TEULADA'), ('10', 'МОРАЙРА / MORAIRA'), ('11', 'ХАВЕА / JAVEA'), ('12', 'ДЕНИЯ / DENIA'), ('13', 'ОНДАРА / ONDARA'), ('14', 'ОЛИВА / OLIVA'), ('15', 'ГАНДИЯ / GANDIA')], max_length=50),
        ),
    ]
