# Generated by Django 2.2.7 on 2019-12-02 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191128_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Start')),
            ],
        ),
        migrations.AlterField(
            model_name='calculate',
            name='kuda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Space'),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Start'),
        ),
        migrations.AlterField(
            model_name='calculate',
            name='type_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TypeCar'),
        ),
        migrations.AddField(
            model_name='space',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Start'),
        ),
    ]
