# Generated by Django 2.2.7 on 2019-12-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20191202_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typecar',
            name='start',
        ),
    ]
