# Generated by Django 3.0 on 2019-12-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_typecar_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='start',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
